---
- name: Configure machine with AtomicRedTeam
  hosts: windows

  tasks:
  - name: Install Sysmon
    import_role:
      name: ansible-sysmon
  - name: Disable Windows Defender For Endpoint - Create Key
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
  - name: Disable Windows Defender For Endpoint - Add Value
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
      name: DisableRealtimeMonitoring
      data: 1
      type: dword
  - name: Disable Windows Defender for Endpoint using the GUI
    pause:
  - name: Ensure that WinRM is started when the system has settled
    win_service:
      name: WinRM
      start_mode: auto
  - name: Reboot the machine
    ansible.windows.win_reboot:
  - name: Install Invoke-AtomicRedTeam with Atomics
    ansible.windows.win_powershell:
      script: |
        Install-PackageProvider -Name NuGet -Force
        IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing);
        Install-AtomicRedTeam -getAtomics -Force
