---
- name: Configure Lab VM with Sysmon, Hedera, and AtomicRedTeam. Finally, disable Defender for Endpoint
  hosts: windows

  tasks:
  - name: Install Sysmon
    import_role:
      name: ansible-sysmon

  - name: Install Sigma
    import_role:
      name: ansible-sigma

  - name: Install Hedera
    import_role:
      name: ansible-hedera
  
  # Install python runtime and libraries

  - name: Install the python runtime package
    ansible.windows.win_package:
      path: "https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe"
      product_id: '{ceda1852-a84a-42fc-beaf-5ea08647fe56}'
      arguments: /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_pipe=1
  
  - name: Install pyyaml and requests with pip
    ansible.windows.win_shell: pip install pyyaml requests
  
  
  - name: Disable Windows Defender For Endpoint - Create Key
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
  
  - name: Disable Windows Defender For Endpoint - Add Value
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
      name: DisableRealtimeMonitoring
      data: 1
      type: dword
  
  - name: Disable Windows Defender for Endpoint using the GUI
    pause:
  
  - name: Ensure that WinRM is started when the system has settled
    win_service:
      name: WinRM
      start_mode: auto
  
  - name: Reboot the machine
    ansible.windows.win_reboot:
  
  - name: Install Invoke-AtomicRedTeam with Atomics
    ansible.windows.win_powershell:
      script: |
        Install-PackageProvider -Name NuGet -Force
        IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing);
        Install-AtomicRedTeam -getAtomics -Force
