version: "3.8"
services:
  thehive:
    image: thehiveproject/thehive4:latest
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
    volumes:
      - ./vol/thehive/application.conf:/etc/thehive/application.conf
      - ./vol/thehive/db:/opt/thp/thehive/db
      - ./vol/thehive/index:/opt/thp/thehive/index
      - ./vol/thehive/data:/opt/thp/thehive/data
    command: --no-config --no-config-secret