---
# defaults file for ansible-sigma
# https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe
# .\python.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_pipe=1
# pip3 install pyyaml requests

- name: Get sigma zip
  win_get_url:
    url: "{{sigma_zip_base_url}}/{{sigma_zip_version}}//{{zip_extension}}"
    dest: "{{sigma_install_location}}/{{sigma_zip_file}}"

- name: Unzip sigma
  win_unzip:
    src: "{{sigma_install_location}}/{{sigma_zip_file}}"
    dest: "{{sigma_install_location}}"
    delete_archive: yes
  register: result

