<#
.SYNOPSIS

Shows the scan result using Out-GridView PowerShell cmdlet.

.DESCRIPTION

This PowerShell module permitts to show the result of an Hedera Scan session using a simple UI.
For each type of scan, Hedera generates different json file that could be ingest inside a SIEM or show locally using Out-GridView cmdlet.

.PARAMETER LogPath

Specifies the log path generated by Hedera

.PARAMETER LogType

Specifies the log type generated by Hedera

.EXAMPLE

PS> Import-Module .\logs_viewer.psm1
PS> Get-HederaLogUI -LogPath .\registry_evidences.json -LogType registry

.EXAMPLE

PS> Import-Module .\logs_viewer.psm1
PS> Get-HederaLogUI -LogPath .\file_evidences.json -LogType file

.EXAMPLE

PS> Import-Module .\logs_viewer.psm1
PS> Get-HederaLogUI -LogPath .\pipe_evidences.json -LogType pipe

#>


Add-Type -AssemblyName System.Web.Extensions
function Get-HederaLogUI
{
    Param(
        [Alias("Log")]
        [Parameter(Mandatory, Position=0)]
        [String] $LogPath,

        [Alias("Type")]
        [Parameter(Mandatory, Position=1)]
        [ValidateSet('registry','file','pipe','process')]
        [String] $LogType
    )
    
    Begin{

        $GridViewColumnConfig = @{ 

                registry = [array] @(
                    @{ Name = 'DateTime'; Expression = { $_.DATETIME_Datetime } }, 
                    @{ Name = 'Result'; Expression = { $_.Result } }, 
                    @{ Name = 'GUID'; Expression = { $_.RegistryIndicator.Guid } }, 
                    @{ Name = 'Type'; Expression = { $_.RegistryIndicator.Type } }, 
                    @{ Name = 'BaseKey'; Expression = { $_.RegistryIndicator.BaseKey } }, 
                    @{ Name = 'Key'; Expression = { $_.RegistryIndicator.Key } },  
                    @{ Name = 'ValueNameRegEx'; Expression = { $_.RegistryIndicator.ValueNameRegex } },
                    @{ Name = 'ValueDataRegEx'; Expression = { $_.RegistryIndicator.ValueDataRegex } },
                    @{ Name = 'Key Path'; Expression = { $_.RegistryItem.STRING_Name } },
                    @{ Name = 'ValueName'; Expression = { $_.RegistryItem.STRING_ValueName } }, 
                    @{ Name = 'ValueData'; Expression = { $_.RegistryItem.OBJECT_ValueData } }
                )

                file = [array] @(
                    @{ Name = 'DateTime'; Expression = { $_.DATETIME_Datetime } }, 
                    @{ Name = 'Result'; Expression = { $_.Result } }, 
                    @{ Name = 'GUID'; Expression = { $_.FileIndicator.Guid } }, 
                    @{ Name = 'Type'; Expression = { $_.FileIndicator.Type } },
                    @{ Name = 'Sha256'; Expression = { $_.FileIndicator.Sha256Hash } },
                    @{ Name = 'IMPHASH'; Expression = { $_.FileIndicator.Value } },
                    @{ Name = 'Path'; Expression = { $_.FileIndicator.Path } },
                    @{ Name = 'FileName'; Expression = { $_.FileIndicator.Filename } },
                    @{ Name = 'Yara Rule'; Expression = { $_.FileIndicator.Rule } },
                    @{ Name = 'Detected Path'; Expression = { $_.FileItem.STRING_Path } }
                   
                )

                pipe = [array] @(
                    @{ Name = 'DateTime'; Expression = { $_.DATETIME_Datetime } }, 
                    @{ Name = 'Result'; Expression = { $_.Result } }, 
                    @{ Name = 'GUID'; Expression = { $_.PipeIndicator.Guid } }, 
                    @{ Name = 'Type'; Expression = { $_.PipeIndicator.Type } },
                    @{ Name = 'NameRegex'; Expression = { $_.PipeIndicator.Name } },
                    @{ Name = 'Name'; Expression = { $_.Name } }
                )

                process = [array] @(
                    @{ Name = 'DateTime'; Expression = { $_.DATETIME_Datetime } }, 
                    @{ Name = 'Result'; Expression = { $_.Result } }, 
                    @{ Name = 'GUID'; Expression = { $_.ProcessIndicator.Guid } }, 
                    @{ Name = 'Type'; Expression = { $_.ProcessIndicator.Type } },
                    @{ Name = 'Name'; Expression = { $_.ProcessIndicator.Name } }, 
                    @{ Name = 'Sha256'; Expression = { $_.ProcessIndicator.Sha256Hash } },

                    @{ Name = 'ProcessName'; Expression = { $_.Name } }
                )
        }
    }

    Process{

        
        # Instantiates the JSON Deserialize Class
        $jsonDeserializer = New-Object -TypeName System.Web.Script.Serialization.JavaScriptSerializer
        # Sets the MAX Json Length Threshold to 100MB
        $jsonDeserializer.MaxJsonLength = 104857600 
        
        # Reads the JSON log file content
        $STRING_FileContent = [System.IO.File]::ReadAllText($LogPath)
        # Deserializes the JSON buffer
        $OBJECT_DeserializedJSON = $jsonDeserializer.Deserialize($STRING_FileContent, [System.Object])
        # Disposes the buffer
        $STRING_FileContent = $null
        # Disposes the JSON Deserialer object
        $jsonDeserializer = $null

        $OBJECT_DeserializedJSON | Select-Object -Property $GridViewColumnConfig.$LogType | Out-GridView  -Title "Scan result for ${LogType} indicators, File: ${LogPath} "
    }

    End{

    }
}

Export-ModuleMember -Function Get-HederaLogUI