---

- name: Install the python runtime package
  ansible.windows.win_package:
    path: "{{python_package_url}}"
    product_id: '{ceda1852-a84a-42fc-beaf-5ea08647fe56}'
    arguments: /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_pipe=1
  
- name: Install pyyaml and requests with pip
  ansible.windows.win_shell: pip install {{python_dependencies}}

- name: Install the dotnet runtime package
  ansible.windows.win_package:
    path: "{{dotnet_package_url}}"
    product_id: '{ceda1852-a84a-42fc-beaf-5ea08647fd64}'
    arguments: /install /passive /norestart